"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import pymysql
from env import *
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 从环境变量读取，如果没有则使用默认值，但生产环境必须设置
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-y(df$uwnha$0nrkmh5g(ri^=^#3qru3bf8$pw+t6e_wb*op7gj')

# 生产环境检查 SECRET_KEY
if SECRET_KEY == 'django-insecure-y(df$uwnha$0nrkmh5g(ri^=^#3qru3bf8$pw+t6e_wb*op7gj' and not DEBUG:
    raise ValueError("DJANGO_SECRET_KEY must be set in production environment")

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'channels',  # WebSocket支持
    'core',
    'scheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'common.middleware.SecurityHeadersMiddleware',  # 新增安全头中间件
    # 'common.middleware.ApiLoggingMiddleware',
]

ROOT_URLCONF = 'application.urls'
AUTH_USER_MODEL = 'core.User'

WSGI_APPLICATION = 'application.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 数据库配置
if DATABASE_TYPE == "MYSQL":
    # Mysql数据库
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
        }
    }
elif DATABASE_TYPE == "SQLSERVER":
    # SqlServer数据库
    DATABASES = {
        "default": {
            "ENGINE": "mssql",
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
            # 全局开启事务，绑定的是http请求响应整个过程
            'ATOMIC_REQUESTS': True,
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
            },
        }
    }
elif DATABASE_TYPE == "POSTGRESQL":
    # POSTGRESQL
    DATABASES = {
        "default": {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
            # 全局开启事务，绑定的是http请求响应整个过程
            'ATOMIC_REQUESTS': True,
        },
    }
else:
    # sqlite3 数据库
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }

# 数据库路由器配置
# DATABASE_ROUTERS = ['application.db_router.DatabaseRouter']

# 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'{REDIS_URL}/{REDIS_DB}',
        "TIMEOUT": None,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

# # ================================================= #
# # ********************* 日志配置 ******************* #
# # ================================================= #

SERVER_LOGS_FILE = os.path.join(BASE_DIR, "logs", "server.log")
ERROR_LOGS_FILE = os.path.join(BASE_DIR, "logs", "error.log")
LOGS_FILE = os.path.join(BASE_DIR, "logs")
if not os.path.exists(os.path.join(BASE_DIR, "logs")):
    os.makedirs(os.path.join(BASE_DIR, "logs"))

# 格式:[2020-04-22 23:33:01][micoservice.apps.ready():16] [INFO] 这是一条日志:
# 格式:[日期][模块.函数名称():行号] [级别] 信息
STANDARD_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
CONSOLE_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": STANDARD_LOG_FORMAT},
        "console": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "file": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": SERVER_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 10,  # 100 MB
            "backupCount": 5,  # 最多备份5个
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": ERROR_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 10,  # 100 MB
            "backupCount": 3,  # 最多备份3个
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "console",
        },

    },
    "loggers": {
        "": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
            "propagate": False,
        },
        'django.db.backends': {
            'handlers': ["console", "error", "file"],
            'propagate': False,
            'level': "INFO"
        },
        "uvicorn.error": {
            "level": "INFO",
            "handlers": ["console", "error", "file"],
        },
        "uvicorn.access": {
            "handlers": ["console", "error", "file"],
            "level": "INFO"
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# # ================================================= #
# # ******************** Celery 配置 ***************** #
# # ================================================= #
CELERY_BROKER_URL = f'{REDIS_URL}/2'
DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_ENABLE_UTC = False
CELERY_WORKER_CONCURRENCY = 2  # 并发数
CELERY_MAX_TASKS_PER_CHILD = 5  # 没个worker最多执行5个任务便自我销毁释放内存
CELERY_TIMEZONE = TIME_ZONE  # celery 时区问题
CELERY_RESULT_BACKEND = 'django-db'  # celery结果存储到数据库中

# # ================================================= #
# # ******************** JWT 配置 ***************** #
# # ================================================= #

# 生产环境验证密钥已配置
if not DEBUG:
    if JWT_ACCESS_SECRET_KEY == 'default-access-secret-key-change-in-production':
        raise ValueError("JWT_ACCESS_SECRET_KEY must be set in production environment")
    if JWT_REFRESH_SECRET_KEY == 'default-refresh-secret-key-change-in-production':
        raise ValueError("JWT_REFRESH_SECRET_KEY must be set in production environment")

JWT_ALGORITHM = "HS256"
# 修复：缩短 token 过期时间
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.environ.get('JWT_ACCESS_TOKEN_EXPIRE_MINUTES', 60 * 24))  # 默认1小时
JWT_REFRESH_TOKEN_EXPIRE_MINUTES = int(os.environ.get('JWT_REFRESH_TOKEN_EXPIRE_MINUTES', 60 * 24 * 7))  # 默认7天


# # ================================================= #
# # ******************** 邮箱 配置 ***************** #
# # ================================================= #

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'  # 邮件服务器地址
EMAIL_PORT = 25  # 邮件服务器端口
EMAIL_USE_TLS = False  # 是否使用 TLS
EMAIL_HOST_USER = ''  # 发件人邮箱
EMAIL_HOST_PASSWORD = ''  # 发件人邮箱密码

# 接口白名单，不需要授权直接访问 - 修复：缩小范围
API_WHITE_LIST = [
    # '/api/core/login',  # 登录接口
    # '/api/core/login_v5',  # V5登录接口
    # '/api/core/register',  # 注册接口
    # '/api/core/menu/route/tree',  # 菜单路由树
    # '/api/syscoretem/server_monitor/*',  # 服务器监控
]

API_LOG_ENABLE = False
ENABLE_LOGIN_ANALYSIS_LOG = False
API_LOG_METHODS = ['POST', 'GET', 'DELETE', 'PUT']
API_MODEL_MAP = {}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # ================================================= #
# # ******************** 安全配置 ***************** #
# # ================================================= #

# HTTPS 和安全头配置
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
# SameSite Cookie
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SAMESITE = 'Strict'

# 安全 HTTP 头
SECURE_HSTS_SECONDS = 31536000  # 1年
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# 防止内容类型嗅探
SECURE_CONTENT_TYPE_NOSNIFF = True

# 点击劫持防护
X_FRAME_OPTIONS = 'DENY'

# ================================================= #
# ********************* 文件存储配置 ******************* #
# ================================================= #

# 文件存储类型: local, oss, minio, azure
FILE_STORAGE_TYPE = 'local'

# 本地存储配置
FILE_STORAGE_LOCAL_PATH = os.path.join(BASE_DIR, 'media', 'file_manager')

# 阿里云OSS配置
OSS_ENDPOINT = ''
OSS_ACCESS_KEY_ID = ''
OSS_ACCESS_KEY_SECRET = ''
OSS_BUCKET_NAME = ''

# Minio配置
MINIO_ENDPOINT = ''
MINIO_ACCESS_KEY = ''
MINIO_SECRET_KEY = ''
MINIO_BUCKET_NAME = ''

# Azure Blob配置
AZURE_ACCOUNT_NAME = ''
AZURE_ACCOUNT_KEY = ''
AZURE_CONTAINER_NAME = ''

# ================================================= #
# ********************* AAD配置 ******************* #
# ================================================= #

# Azure AD 租户ID
AAD_TENANT_ID = ''

# Azure AD 应用程序(客户端) ID
AAD_CLIENT_ID = ''

# 如果需要验证特定的租户，可以设置为具体的租户ID
# AAD_TENANT_ID = 'your-tenant-id'


# ============前端版本 v5为Vben V5，v2位Vben2================== #

# ================================================= #
# ********************* Channels WebSocket配置 ******************* #
# ================================================= #

# ASGI 应用程序
ASGI_APPLICATION = 'application.asgi.application'

# Channels 层配置
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:6379/{REDIS_DB}"],
            "symmetric_encryption_keys": [SECRET_KEY],
        },
    },
}

DEFAULT_PASSWORD = "123456"

# ================================================= #
# ********************* 阿里云短信服务配置 ******************* #
# ================================================= #

# 阿里云短信服务配置
ALIYUN_SMS_ACCESS_KEY_ID = ""  # 请填入您的AccessKey ID
ALIYUN_SMS_ACCESS_KEY_SECRET = ""  # 请填入您的AccessKey Secret
ALIYUN_SMS_SIGN_NAME = ""  # 请填入您的短信签名
ALIYUN_SMS_TEMPLATE_CODE = ""  # 请填入您的短信模板代码